version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "ai/slackbot-mcp-client/no-auth"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "ai/slackbot-mcp-client/slack-identity"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "block-kit"
    schedule:
      interval: "daily"
