name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: "pytest@python3.14"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        showcase:
          - "ai/slackbot-mcp-client/no-auth"
          - "ai/slackbot-mcp-client/rich-responses/mcp-apps"
          - "ai/slackbot-mcp-client/slack-identity"
          - "block-kit"
          - "methods"
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
      - name: Run tests
        run: |
          cd "${{ matrix.showcase }}"
          pip install -r requirements.txt
          ruff check
          ruff format --diff --check
          mypy .
          if [ -d tests ]; then pytest -v; fi
